// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrrnztnbfgezeefumekf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycm56dG5iZmdlemVlZnVtZWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjk0MjUsImV4cCI6MjA2NTYwNTQyNX0.MutwUPIGNi8v0qDvA0sX-olyxbuKgPkCekBDGXkMVqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);